#!/bin/bash

echo "Attempting RDP to $1"
#server=$(echo ${1} | sed -r -e s/\\..*//)
domain=.hq.sdamedia.com
target=$1${domain}
xfreerdp /u:rdunn /size:1920x1060 /t:$1 /v:${target} -grab-keyboard 

#i3-msg 'workspace $rdp'
