#!/bin/bash
## regenerate grub.cfg in /boot/grub/grub.cfg and replace boot.efi on /dev/sda4
set +v
set +x
mount -t hfsplus -o force,rw /dev/sda4 /mnt
grub-mkconfig -o /boot/grub/grub.cfg
grub-mkstandalone -o /mnt/System/Library/CoreServices/boot.efi -d /usr/lib/grub/x86_64-efi -O x86_64-efi /boot/grub/grub.cfg
set -v
set -x
