#!/bin/bash
echo "Adjusting for three displays"
#xrandr --output eDP-1 --auto --pos 0x0 --output DP-2 --auto --scale 1.38x1.38 --pos 2880x0 --output HDMI-1 --auto --scale 1.38x1.38 --pos 5536x0 --fb 8192x1800
xrandr --output eDP-1 --off
xrandr --output DP-2 --auto --scale 1.38x1.38 --left-of HDMI-1 --pos 0x0
xrandr --output HDMI-1 --auto --scale 1.38x1.38 --pos 2650x0
